safe: true
lsi: false
pygments: true
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb']
permalink: :pretty

### MVP infos
mvp:
  number_of_projects: 55

  projects:
    -
      name: MyHumble
      url: "http://www.myhumble.com.br"
      image: /images/projetos/mvp/my-humble.jpg
    -
      name: Perfil Plug
      url: "http://www.perfilplug.com"
      image: /images/projetos/mvp/perfilplug.jpg
    # -
    #   name: Assed & Cavalcante
    #   url: "http://www.assedcavalcante.com.br/"
    #   image: /images/projetos/mvp/assed-cavalcante.jpg
    -
      name: Sala de Ideias
      url: "http://www.saladeideias.com.br/"
      image: /images/projetos/mvp/saladeideias.jpg
    -
      name: Niili
      url: "http://www.niili.com.br/"
      image: /images/projetos/mvp/niili.jpg
    # -
    #   name: Samba Ads
    #   url: "#"
    #   image: /images/projetos/mvp/sambaads.jpg
    -
      name: Sou do Esporte
      url: http://www.soudoesporte.com.br
      image: /images/projetos/mvp/soudoesporte.jpg
    # -
    #   name: Seu Orientador
    #   url: http://www.seuorientador.com.br
    #   image: /images/projetos/mvp/seuorientador.jpg
    # -
    #   name: BRtrax
    #   url: http://app.brtrax.com
    #   image: /images/projetos/mvp/brtrax.jpg
    -
      name: RIO EM FOCO
      url: http://www.rioemfoco.com.br
      image: /images/projetos/mvp/rioemfoco.jpg
    -
      name: Dunno
      url: http://www.dunno.vc
      image: /images/projetos/mvp/dunno.jpg
    -
      name: Vita Corporativa
      url: "http://www.vitacorporativa.com.br/"
      image: /images/projetos/mvp/vitacorporativa.jpg
    -
      name: Alugue Campo e Praia
      url: http://www.aluguecampoepraia.com.br/
      image: /images/projetos/mvp/alugue-campo-e-praia.jpg
    -
      name: Timeeline
      url: http://www.timeeline.com/
      image: /images/projetos/mvp/timeeline.jpg
    -
      name: Meu Baby Chá
      url: http://www.meubabycha.com.br/
      image: /images/projetos/mvp/meu-baby-cha.jpg
    # -
    #   name: Tempo Eh Dinheiro
    #   url: http://www.tempoehdinheiro.com.br/
    #   image: /images/projetos/mvp/tempo-eh-dinheiro.jpg
    # -
    #   name: "Click&amp;Movimento"
    #   url: http://www.clickemovimento.com.br
    #   image: /images/projetos/mvp/clickemovimento.jpg
    # -
    #   name: MIIDAH
    #   url: http://app.miidah.com
    #   image: /images/projetos/mvp/miidah.jpg
    -
      name: GiftBar
      url: http://app.giftbar.com.br/
      image: /images/projetos/mvp/giftbar.jpg
    # -
    #   name: Xtools
    #   url: "#"
    #   image: /images/projetos/mvp/xtools.jpg
    # -
    #   name: Cuponizando
    #   url: http://ofertas.cuponizando.com.br/
    #   image: /images/projetos/mvp/cuponizando.jpg
    -
      name: Innterpretti
      url: http://www.innterpretti.com.br/
      image: /images/projetos/mvp/innterpretti.jpg
    # -
    #   name: Orçamento Rápido
    #   url: http://app.orcamentorapido.com.br/
    #   image: /images/projetos/mvp/orcamento-rapido.jpg
    -
      name: Incrível MEMO
      url: http://incrivelmemo.com.br/
      image: /images/projetos/mvp/memo.jpg
    -
      name: Mo Recipes
      url: http://morecipes.com.br/
      image: /images/projetos/mvp/morecipes.jpg
    # -
    #   name: Horus
    #   url: "#"
    #   image: /images/projetos/mvp/horus.jpg
    -
      name: managerbook
      url: http://managerbook.com.br/
      image: /images/projetos/mvp/managerbook.jpg
    -
      name: Feedback Machine
      url: http://app.feedback-machine.com/
      image: /images/projetos/mvp/feedback-machine.jpg
    # -
    #   name: Hintask
    #   url: http://hintask.com/
    #   image: /images/projetos/mvp/hintask.jpg
    # -
    #   name: Shop My Shop
    #   url: "#"
    #   image: /images/projetos/mvp/shopmyshop.jpg
    # -
    #   name: SMB Challenge
    #   url: http://smbchallenge.com/
    #   image: /images/projetos/mvp/smbchallenge.jpg
    # -
    #   name: neighbourz
    #   url: http://app.neighbourz.com
    #   image: /images/projetos/mvp/neighbourz.jpg
    # -
    #   name: hospedfácil
    #   url: "#"
    #   image: /images/projetos/mvp/hospedfacil.jpg
    -
      name: Landing Commerce
      url: http://app.landingcommerce.com.br/
      image: /images/projetos/mvp/landing-commerce.jpg
    -
      name: Mamãe eu Kero
      url: http://www.mamaeeukero.com.br/
      image: /images/projetos/mvp/mamaeeukero.jpg
    -
      name: WEBSIMULADO
      url: http://www.websimulado.com.br/
      image: /images/projetos/mvp/websimulado.jpg
    -
      name: Alik
      url: http://www.alik.com.br/
      image: /images/projetos/mvp/alik.jpg
    -
      name: NoTrombone
      url: http://www.notrombone.com/
      image: /images/projetos/mvp/no-trambone.jpg
    # -
    #   name: Editora TIL
    #   url: "#"
    #   image: /images/projetos/mvp/no-screen.jpg
    # -
    #   name: Game Quiz
    #   url: http://apps.facebook.com/gamequizbr/
    #   image: /images/projetos/mvp/gamequiz.jpg
    -
      name: Given 2 You
      url: http://www.gv2u.com.br/
      image: /images/projetos/mvp/given2you.jpg
    # -
    #   name: Sparkel
    #   url: "#"
    #   image: /images/projetos/mvp/sparkel.jpg
    -
      name: Estou Jogando
      url: http://estoujogando.com.br/
      image: /images/projetos/mvp/estou-jogando.jpg
    # -
    #   name: Shopping Passion
    #   url: "#"
    #   image: /images/projetos/mvp/shopping-passion.jpg
    -
      name: LetsEvo
      url: http://www.designoteca.com/
      image: /images/projetos/mvp/letsevo.jpg
    -
      name: Netadvocacia
      url: http://www.netadvocacia.com.br/
      image: /images/projetos/mvp/netadvocacia.jpg
    -
      name: Ultrapasse
      url: "http://www.ultrapasseweb.com/"
      image: /images/projetos/mvp/ultrapasse.jpg
    # -
    #   name: Publication of Labels
    #   url: "#"
    #   image: /images/projetos/mvp/pol.jpg
    # -
    #   name: Turbotaxi
    #   url: "#"
    #   image: /images/projetos/mvp/turbotaxi.jpg
    # -
    #   name: Propsharely
    #   url: "http://www.propsharely.com/"
    #   image: /images/projetos/mvp/propsharely.jpg
    # -
    #   name: LMT
    #   url: https://www.likemytip.com.br/
    #   image: /images/projetos/mvp/likemytip.jpg
    -
      name: Zupty
      url: http://www.zupty.com/
      image: /images/projetos/mvp/zupty.jpg
    -
      name: Amigo não se Compra
      url: http://www.amigonaosecompra.com.br/
      image: /images/projetos/mvp/amigo-nao-se-compra.jpg
    # -
    #   name: Sabtudo
    #   url: "http://www.sabtudo.com.br/"
    #   image: /images/projetos/mvp/sabtudo.jpg
    -
      name: Safe Tracking
      url: http://safetracking.com.br/
      image: /images/projetos/mvp/safe-tracking.jpg
    -
      name: ContaCal
      url: http://app.contacal.com.br/
      image: /images/projetos/mvp/contacal.jpg
    -
      name: SocialFly
      url: http://www.socialfly.com.br/
      image: /images/projetos/mvp/socialfly.jpg
    -
      name: MeaPets
      url: http://www.meapets.com.br/
      image: /images/projetos/mvp/meapets.jpg
    -
      name: The Open Compass
      url: http://www.theopencompass.com/
      image: /images/projetos/mvp/the-open-compass.jpg
    # -
    #   name: Rank Monitor
    #   url: "#"
    #   image: /images/projetos/mvp/rank-monitor.jpg
    # -
    #   name: Ideias
    #   url: "#"
    #   image: /images/projetos/mvp/ideias.jpg

  testimonials:
    -
      name: "Milton Menezes"
      company: "Vita Corporativa"
      description: "O que mais me chamou a atenção foi a forma focada e objetiva que a equipe trabalhou desde a primeira Etapa da reunião sobre o Projeto. Os tempos definidos foram cumpridos rigorosamente, quase cronometrados. As sugestões apresentadas, quando cada um apresentou suas telas, ajudaram a enriquecer o sistema, mesmo não sendo aplicadas, pois acabam mantendo o pensamento 'aquecido' sobre o melhor funcionamento do Sistema."
    -
      name: "Lucas Boscacci Lima"
      company: "Dunno"
      description: "Depois de uma semana do trabalho feito, muita coisa acontece, mas fica a lembrança memorável do trabalho com a equipe da HE Labs. Agradeço pela seriedade e emprenho apresentado nos 3 dias do Startup Dev. Pela minha experiência, no cenário atual de desenvolvimento de aplicações, é muito difícil encontrar a qualidade do serviço de vocês. Ainda mais difícil é encontrar uma equipe que consiga agregar real valor para o serviço. Valor este que está na energia e empenho de se trabalhar com paixão"
    -
      name: "Matheus Diaz e Ronnie Possatti"
      company: "Horus"
      description: "O serviço prestado pela Startup DEV superou nossas expectativas. Conseguimos priorizar exatamente os pontos mais importantes nesta primeira etapa. Temos certeza que produto desenvolvido com qualidade e agilidade foi um ótimo primeiro passo para o nosso projeto! Obrigado pela experiência."
    -
      name: "José Roberto H. da Gama"
      company: "NetAdvocacia"
      description: "os aconselhamentos técnicos fizeram toda a diferença, pois a sensação ao final foi de ter recebido mais do que havia sido planejado e contratado."
    -
      name: "Kauê Linden"
      company: "Game Guiz"
      description: "O processo foi uma verdadeira aula de como organizar projetos ligados ao desenvolvimento de software"
    -
      name: "Amure Pinho"
      company: "Amigo Não Se Compra / SyncMobile"
      description: "O conhecimento técnico e a habilidade do time em entender o projeto e desenhar o MVP não só garante a entrega do projeto dentro do prazo excepcional como torna o produto mais inteligente."
    -
      name: "Andre Diamand"
      company: "Zupty / VentureOne"
      description: "A equipe do Startup DEV não tráz somente o software amado em 3 dias, neste período eles nos ensinam na prática o que é um projeto LEAN de verdade, tocado com muita qualidade e capricho."
    -
      name: "Pablo Braga"
      company: "Safetracking / Sidetech"
      description: "O sistema de pontos te dá flexibilidade para definir o que é realmente prioritário e você pode desenvolver o restante posteriormente, quando os clientes ou investidores se interessarem pelo seu projeto."

  testimonials-en:
    -
      name: "Matheus Diaz e Ronnie Possatti"
      company: "Horus"
      description: "The Startup DEV service has overcome our expectations. We were able to emphasize exactly the most important targets for the first stage. We're quite sure that the quickly and skillfully developed product was a great first step for our project! Thank you for the experience."
    -
      name: "Rodrigo Soares"
      company: "Hintask"
      description: "We can only thank Startup DEV. The development team was extremely professional and managed to surpass all expectations. To have a fully functional prototype with a design of choice in 48 hours is something monstrous. Congratulations!"
    -
      name: "José Roberto H. da Gama"
      company: "NetAdvocacia"
      description: "My experience with Startup DEV was great. The work was focused, delivered on time and with quality. Moreover, the technical advice made ​​all the difference, for the feeling at the end was to have received more than what had been planned and paid for."
    -
      name: "Kauê Linden"
      company: "Game Guiz"
      description: "To develop our project through Startup DEV was the quickest way I found to get the project we envisioned on air. Besides leaving satisfied with my design online in just three days, the process was a real lesson on how to organize projects related to software development. I recommend it and I'm sure I will be back soon for other rounds."
    -
      name: "Amure Pinho"
      company: "Amigo Não Se Compra / SyncMobile"
      description: "The work done by the team at Startup DEV is fantastic. Technical knowledge and the ability of the team to understand the project and draw the MVP not only ensures the delivery of the project within an exceptional time frame, but it makes the final product smarter. I really approve it!"
    -
      name: "Diego Ivo"
      company: "Rank Monitor"
      description: "With the help of the Startup DEV staff, Conversion could market an innovative SEO tool, simple and very functional. Our tool had millions of pageviews, which was very important to us."
    -
      name: "Andre Diamand"
      company: "Zupty / VentureOn"
      description: "The Startup DEV team not only brings the beloved software in three days, but in this time they also teach us in practice what is a real LEAN project, conducted with quality and care."
    -
      name: "Pablo Braga"
      company: "Safetracking / Sidetech"
      description: "Sidetech's experience with Startup DEV was very good. The proposed format is very productive because during the initial meeting it uses techniques which give an overview of the project before you even start. The points system gives you the flexibility to define what is really a priority and what can be developed later, when customers or investors take an interest in your project. <br> The staff is super capable and the development work was actually done in 48 hours."
    -
      name: "Joaquim Torres"
      company: "ContaCal"
      description: "The Startup DEV staff was essential to the realization of ContaCal. They not only know a lot about software development, but they have lots of experience in the web business, which makes them great partners for creating an MVP."
    -
      name: "Mario Sousa de Alencar"
      company: "Shopping Passion"
      description: "I can confirm that Startup DEV is full of extremely experienced people providing a great service for those who wish to start a business on the internet but do not have the technological knowledge to do it. However, the methodology is also very effective for entrepreneurs who already have a clearly defined MVP, so that in fact the idea can be transformed into a prototype to be tested."
