server: true
auto: true
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb']
permalink: :pretty

projects:
  -
    name: RIO EM FOCO
    url: http://www.rioemfoco.com.br
    image: /images/projetos/rioemfoco.png
  -
    name: Dunno
    url: http://www.dunno.vc
    image: /images/projetos/dunno.png
  -
    name: Vita Corporativa
    url: "#"
    image: /images/projetos/vitacorporativa.png
  -
    name: Alugue Campo e Praia
    url: http://www.aluguecampoepraia.com.br/
    image: /images/projetos/alugue-campo-e-praia.png
  -
    name: Timeeline
    url: http://www.timeeline.com/
    image: /images/projetos/timeeline.png
  -
    name: Meu Baby Chá
    url: http://www.meubabycha.com.br/
    image: /images/projetos/meu-baby-cha.png
  -
    name: Tempo Eh Dinheiro
    url: http://www.tempoehdinheiro.com.br/
    image: /images/projetos/tempo-eh-dinheiro.png
  -
    name: "Click&amp;Movimento"
    url: http://www.clickemovimento.com.br
    image: /images/projetos/clickemovimento.png
  -
    name: MIIDAH
    url: http://app.miidah.com
    image: /images/projetos/miidah.png
  -
    name: GiftBar
    url: http://app.giftbar.com.br/
    image: /images/projetos/giftbar.png
  -
    name: Xtools
    url: "#"
    image: /images/projetos/xtools.png
  -
    name: Cuponizando
    url: http://ofertas.cuponizando.com.br/
    image: /images/projetos/cuponizando.png
  -
    name: Innterpretti
    url: http://www.innterpretti.com.br/
    image: /images/projetos/innterpretti.png
  -
    name: Orçamento Rápido
    url: http://app.orcamentorapido.com.br/
    image: /images/projetos/orcamento-rapido.png
  -
    name: Incrível MEMO
    url: http://incrivelmemo.com.br/
    image: /images/projetos/memo.png
  -
    name: Mo Recipes
    url: http://morecipes.com.br/
    image: /images/projetos/morecipes.png
  -
    name: Horus
    url: "#"
    image: /images/projetos/horus.png
  -
    name: managerbook
    url: http://managerbook.com.br/
    image: /images/projetos/managerbook.png
  -
    name: Feedback Machine
    url: http://app.feedback-machine.com/
    image: /images/projetos/feedback-machine.png
  -
    name: Hintask
    url: http://hintask.com/
    image: /images/projetos/hintask.png
  -
    name: Shop My Shop
    url: "#"
    image: /images/projetos/shopmyshop.png
  -
    name: SMB Challenge
    url: http://smbchallenge.com/
    image: /images/projetos/smbchallenge.png
  -
    name: neighbourz
    url: http://app.neighbourz.com
    image: /images/projetos/neighbourz.png
  -
    name: hospedfácil
    url: "#"
    image: /images/projetos/hospedfacil.png
  -
    name: Landing Commerce
    url: http://www.landingcommerce.com.br/
    image: /images/projetos/landing-commerce.png
  -
    name: Mamãe eu Kero
    url: http://www.mamaeeukero.com.br/
    image: /images/projetos/mamaeeukero.png
  -
    name: WEBSIMULADO
    url: http://www.websimulado.com.br/
    image: /images/projetos/websimulado.png
  -
    name: Alik
    url: http://www.alik.com.br/
    image: /images/projetos/alik.png
  -
    name: NoTrombone
    url: http://www.notrombone.com/
    image: /images/projetos/no-trombone.png
  -
    name: Editora TIL
    url: "#"
    image: /images/projetos/no-screen.png
  -
    name: Game Quiz
    url: http://apps.facebook.com/gamequizbr/
    image: /images/projetos/gamequiz.png
  -
    name: Given 2 You
    url: http://www.gv2u.com.br/
    image: /images/projetos/given2you.png
  -
    name: Sparkel
    url: "#"
    image: /images/projetos/sparkel.png
  -
    name: Estou Jogando
    url: http://estoujogando.com.br/
    image: /images/projetos/estou-jogando.png
  -
    name: Shopping Passion
    url: "#"
    image: /images/projetos/shopping-passion.png
  -
    name: LetsEvo
    url: http://www.designoteca.com/
    image: /images/projetos/letsevo.png
  -
    name: Netadvocacia
    url: http://www.netadvocacia.com.br/
    image: /images/projetos/netadvocacia.png
  -
    name: Ultrapasse
    url: "#"
    image: /images/projetos/ultrapasse.png
  -
    name: Publication of Labels
    url: "#"
    image: /images/projetos/pol.png
  -
    name: Turbotaxi
    url: "#"
    image: /images/projetos/turbotaxi.png
  -
    name: Propsharely
    url: "#"
    image: /images/projetos/propsharely.png
  -
    name: LMT
    url: https://www.likemytip.com.br/
    image: /images/projetos/likemytip.png
  -
    name: Zupty
    url: http://www.zupty.com/
    image: /images/projetos/zupty.png
  -
    name: Amigo não se Compra
    url: http://www.amigonaosecompra.com.br/
    image: /images/projetos/amigo-nao-se-compra.png
  -
    name: Sabtudo
    url: "#"
    image: /images/projetos/sabtudo.png
  -
    name: Safe Tracking
    url: http://safetracking.com.br/
    image: /images/projetos/safe-tracking.png
  -
    name: ContaCal
    url: http://app.contacal.com.br/
    image: /images/projetos/contacal.png
  -
    name: Rank Monitor
    url: "#"
    image: /images/projetos/rank-monitor.png
  -
    name: Ideias
    url: "#"
    image: /images/projetos/ideias.png

schedule:
  year: 2013
  data:
    -
      month: Abril
      weeks:
        -
          date: 01/04
          client: Mateus Bastos
          status: client
        -
          date: 08/04
          client: Pleimo
          status: client
        -
          date: 15/04
          client: César Augusto
          status: client
        -
          date: 22/04
          client: André Coutrim
          status: client
        -
          date: 29/04
          client: Humberto Ribeiro
          status: client
    -
      month: Maio
      weeks:
        -
          date: 06/05
          client: Thiago Gomes
          status: client
        -
          date: 13/05
          client: Milton Menezes
          status: client
        -
          date: 20/05
          client: Lucas Boscacci
          status: client
        -
          date: 27/05
          client: Vinicius Gonçalves
          status: client
        -
          date:
          status:
    -
      month: Junho
      weeks:
        -
          date: 04/06
          client: BRtrax
          status: client
        -
          date: 11/06
          status: free
        -
          date: 18/06
          status: free
        -
          date: 25/06
          status: free
        -
          date:
          status:

schedule_en:
  year: 2013
  data:
    -
      month:
      weeks:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          status:
    -
      month:
      weeks:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          client:
          status:
        -
          date:
          status:
    -
      month:
      weeks:
        -
          date:
          client:
          status:
        -
          date:
          status:
        -
          date:
          client:
          status:
        -
          date:
          status:
        -
          date:
          status:

