server: true
auto: true
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb']
permalink: :pretty

schedule:
  year: 2013
  data:
    -
      month: Março
      weeks:
        -
          date: 04/03
          client: Bianca Milesi
          status: client
        -
          date: 11/03
          client: George Lavor
          status: client
        -
          date: 18/03
          client: Mauro Ribeiro
          status: client
        -
          date: 25/03
          client: Marcos Andrade
          status: client
        -
          date: 
          status: 
    -
      month: Abril
      weeks:
        -
          date: 01/04
          client: Mateus Bastos
          status: client
        -
          date: 08/04
          status: free
        -
          date: 15/04
          client: César Augusto
          status: client
        -
          date: 22/04
          client: André Coutrim
          status: client
        -
          date: 29/04
          status: unavailable
    -
      month: Maio
      weeks:
        -
          date: 06/05
          status: free
        -
          date: 13/05
          status: free
        -
          date: 20/05
          status: free
        -
          date: 27/05
          status: free
        -
          date: 
          status: 
