server: true
auto: true
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb']
permalink: :pretty

schedule:
  year: 2013
  data:
    -
      month: Fevereiro
      weeks:
        -
          date: 04/02
          client: Yasmin Cunha
          status: client
        -
          date: 11/02
          status: unavailable
        -
          date: 18/02
          status: reserved
        -
          date: 25/02
          client: Bianca Milesi
          status: client
        -
          date: 
          status: 
    -
      month: Março
      weeks:
        -
          date: 04/03
          client: Bianca Milesi
          status: client
        -
          date: 11/03
          client: George Lavor
          status: client
        -
          date: 18/03
          client: Mauro Ribeiro
          status: client
        -
          date: 25/03
          client: Marcos Andrade
          status: client
        -
          date: 
          status: 
    -
      month: Abril
      weeks:
        -
          date: 01/04
          client: Mateus Bastos
          status: client
        -
          date: 08/04
          status: free
        -
          date: 15/04
          status: free
        -
          date: 22/04
          status: unavailable
        -
          date: 29/04
          status: free
