safe: false
highlighter: pygments
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb', 'vendor']
permalink: :pretty

number_of_projects: 80

gems: [bourbon, neat]

sass:
    style: expanded

projects:
  -
    name: Perfil Plug
    url: "http://www.perfilplug.com"
    image: /images/projetos/perfilplug.png
  -
    name: Assed & Cavalcante
    url: "http://www.assedcavalcante.com.br/"
    image: /images/projetos/assed-cavalcante.png
  -
    name: Sala de Ideias
    url: "http://www.saladeideias.com.br/"
    image: /images/projetos/saladeideias.png
  -
    name: Niili
    url: "http://www.niili.com.br/"
    image: /images/projetos/niili.png
  -
    name: Samba Ads
    url: "#"
    image: /images/projetos/sambaads.png
  -
    name: Sou do Esporte
    url: http://www.soudoesporte.com.br
    image: /images/projetos/soudoesporte.png
  -
    name: Seu Orientador
    url: http://www.seuorientador.com.br
    image: /images/projetos/seuorientador.png
  -
    name: BRtrax
    url: http://app.brtrax.com
    image: /images/projetos/brtrax.png
  -
    name: RIO EM FOCO
    url: http://www.rioemfoco.com.br
    image: /images/projetos/rioemfoco.png
  -
    name: Dunno
    url: http://www.dunno.vc
    image: /images/projetos/dunno.png
  -
    name: Vita Corporativa
    url: "http://www.vitacorporativa.com.br/"
    image: /images/projetos/vitacorporativa.png
  -
    name: Alugue Campo e Praia
    url: http://www.aluguecampoepraia.com.br/
    image: /images/projetos/alugue-campo-e-praia.png
  -
    name: Timeeline
    url: http://www.timeeline.com/
    image: /images/projetos/timeeline.png
  -
    name: Meu Baby Chá
    url: http://www.meubabycha.com.br/
    image: /images/projetos/meu-baby-cha.png
  -
    name: Tempo Eh Dinheiro
    url: http://www.tempoehdinheiro.com.br/
    image: /images/projetos/tempo-eh-dinheiro.png
  -
    name: "Click&amp;Movimento"
    url: http://www.clickemovimento.com.br
    image: /images/projetos/clickemovimento.png
  -
    name: MIIDAH
    url: http://app.miidah.com
    image: /images/projetos/miidah.png
  -
    name: GiftBar
    url: http://app.giftbar.com.br/
    image: /images/projetos/giftbar.png
  -
    name: Xtools
    url: "#"
    image: /images/projetos/xtools.png
  -
    name: Cuponizando
    url: http://ofertas.cuponizando.com.br/
    image: /images/projetos/cuponizando.png
  -
    name: Innterpretti
    url: http://www.innterpretti.com.br/
    image: /images/projetos/innterpretti.png
  -
    name: Orçamento Rápido
    url: http://app.orcamentorapido.com.br/
    image: /images/projetos/orcamento-rapido.png
  -
    name: Incrível MEMO
    url: http://incrivelmemo.com.br/
    image: /images/projetos/memo.png
  -
    name: Mo Recipes
    url: http://morecipes.com.br/
    image: /images/projetos/morecipes.png
  -
    name: Horus
    url: "#"
    image: /images/projetos/horus.png
  -
    name: managerbook
    url: http://managerbook.com.br/
    image: /images/projetos/managerbook.png
  -
    name: Feedback Machine
    url: http://app.feedback-machine.com/
    image: /images/projetos/feedback-machine.png
  -
    name: Hintask
    url: http://hintask.com/
    image: /images/projetos/hintask.png
  -
    name: Shop My Shop
    url: "#"
    image: /images/projetos/shopmyshop.png
  -
    name: SMB Challenge
    url: http://smbchallenge.com/
    image: /images/projetos/smbchallenge.png
  -
    name: neighbourz
    url: http://app.neighbourz.com
    image: /images/projetos/neighbourz.png
  -
    name: hospedfácil
    url: "#"
    image: /images/projetos/hospedfacil.png
  -
    name: Landing Commerce
    url: http://app.landingcommerce.com.br/
    image: /images/projetos/landing-commerce.png
  -
    name: Mamãe eu Kero
    url: http://www.mamaeeukero.com.br/
    image: /images/projetos/mamaeeukero.png
  -
    name: WEBSIMULADO
    url: http://www.websimulado.com.br/
    image: /images/projetos/websimulado.png
  -
    name: Alik
    url: http://www.alik.com.br/
    image: /images/projetos/alik.png
  -
    name: NoTrombone
    url: http://www.notrombone.com/
    image: /images/projetos/no-trombone.png
  -
    name: Editora TIL
    url: "#"
    image: /images/projetos/no-screen.png
  -
    name: Game Quiz
    url: http://apps.facebook.com/gamequizbr/
    image: /images/projetos/gamequiz.png
  -
    name: Given 2 You
    url: http://www.gv2u.com.br/
    image: /images/projetos/given2you.png
  -
    name: Sparkel
    url: "#"
    image: /images/projetos/sparkel.png
  -
    name: Estou Jogando
    url: http://estoujogando.com.br/
    image: /images/projetos/estou-jogando.png
  -
    name: Shopping Passion
    url: "#"
    image: /images/projetos/shopping-passion.png
  -
    name: LetsEvo
    url: http://www.designoteca.com/
    image: /images/projetos/letsevo.png
  -
    name: Netadvocacia
    url: http://www.netadvocacia.com.br/
    image: /images/projetos/netadvocacia.png
  -
    name: Ultrapasse
    url: "http://www.ultrapasseweb.com/"
    image: /images/projetos/ultrapasse.png
  -
    name: Publication of Labels
    url: "#"
    image: /images/projetos/pol.png
  -
    name: Turbotaxi
    url: "#"
    image: /images/projetos/turbotaxi.png
  -
    name: Propsharely
    url: "http://www.propsharely.com/"
    image: /images/projetos/propsharely.png
  -
    name: LMT
    url: https://www.likemytip.com.br/
    image: /images/projetos/likemytip.png
  -
    name: Zupty
    url: http://www.zupty.com/
    image: /images/projetos/zupty.png
  -
    name: Amigo não se Compra
    url: http://www.amigonaosecompra.com.br/
    image: /images/projetos/amigo-nao-se-compra.png
  -
    name: Sabtudo
    url: "http://www.sabtudo.com.br/"
    image: /images/projetos/sabtudo.png
  -
    name: Safe Tracking
    url: http://safetracking.com.br/
    image: /images/projetos/safe-tracking.png
  -
    name: ContaCal
    url: http://app.contacal.com.br/
    image: /images/projetos/contacal.png
  -
    name: Rank Monitor
    url: "#"
    image: /images/projetos/rank-monitor.png
  -
    name: Ideias
    url: "#"
    image: /images/projetos/ideias.png

schedule:
  enabled: false
  year: 2016
  data:
    -
      month_pt: Janeiro
      month_en: January
      weeks:
        -
          date: 04/01
          status: unavailable
        -
          date: 11/01
          status: free
        -
          date: 18/01
          status: free
        -
          date: 25/01
          status: free
    -
      month_pt: Fevereiro
      month_en: february
      weeks:
        -
          date: 01/02
          status: free
        -
          date: 08/02
          status: unavailable
        -
          date: 15/02
          status: free
        -
          date: 22/02
          status: free
        -
          date: 29/02
          status: unavailable
