safe: true
lsi: false
pygments: true
exclude: ['Rakefile', 'README', 'Gemfile', 'Gemfile.lock', 'config.rb']
permalink: :pretty


### MVP infos
mvp:
  number_of_projects: 50

  projects:
    -
      name: Sala de Ideias
      url: "http://www.saladeideias.com.br"
      image: /images/projetos/mvp/saladeideias.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Niili
      url: "http://www.niili.com.br"
      image: /images/projetos/mvp/niili.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Sou do Esporte
      url: "http://www.soudoesporte.com.br"
      image: /images/projetos/mvp/soudoesporte.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Seu orientador
      url: "http://www.seuorientador.com.br"
      image: /images/projetos/mvp/seuorientador.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Rio em Foco
      url: "http://www.rioemfoco.com.br"
      image: /images/projetos/mvp/rioemfoco.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Dunno
      url: "http://www.dunno.vc"
      image: /images/projetos/mvp/dunno.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Vita Corporativa
      url: "http://www.vitacorporativa.com.br"
      image: /images/projetos/mvp/vita.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Timeeline
      url: "http://www.timeeline.com"
      image: /images/projetos/mvp/timeeline.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Meu Baby Chá
      url: "http://www.meubabycha.com.br"
      image: /images/projetos/mvp/meubabycha.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Innterpretti
      url: "http://www.innterpretti.com.br"
      image: /images/projetos/mvp/interpretti.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Meu Incrível Memo
      url: "http://incrivelmemo.com.br"
      image: /images/projetos/mvp/memo.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Mo Recipes
      url: "http://morecipes.com.br"
      image: /images/projetos/mvp/morecipes.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"

  testimonials:
    -
      name: "Sabine Bolonhini"
      company: "Sou do Esporte"
      description: "Muito obrigada pelo envolvimento de vocês!   Muito mais do que desenvolver um software, vocês concretizaram o primeiro passo de um sonho nosso!  Parabéns pelo trabalho! Estamos muito satisfeitas!"
    -
      name: "Mauro Ribeiro"
      company: "Miidah"
      description: "O resultado do Startup DEV superou nossas expectativas. Além da entrega no prazo, sistema funcionando sem erros, etc, a 'visão' da equipe da HE:labs apresentada no primeiro dia de desenvolvimento do Startup DEV contribuiu muito para melhorarmos o projeto inicial de MVP que tínhamos."
    -
      name: "Prof. Darwin Ianuskiewtz"
      company: "Seu Orientador"
      description: "Agradeço a atenção de toda a equipe e o tratamento profissional que permitiu que  a seriedade e comprometimento proporcionasse o bom desenvolvimento da proposta."
    -
      name: "Milton Menezes"
      company: "Vita Corporativa"
      description: "O que mais me chamou a atenção foi a forma focada e objetiva que a equipe trabalhou desde a primeira Etapa da reunião sobre o Projeto. Os tempos definidos foram cumpridos rigorosamente, quase cronometrados. As sugestões apresentadas, quando cada um apresentou suas telas, ajudaram a enriquecer o sistema, mesmo não sendo aplicadas, pois acabam mantendo o pensamento 'aquecido' sobre o melhor funcionamento do Sistema."

  schedule:
    year: 2013
    data:
      -
        month: Junho
        weeks:
          -
            date: 04/06
            client: BRtrax
            status: client
          -
            date: 11/06
            client: Darwin Ianuskiewtz
            status: client
          -
            date: 18/06
            status: free
          -
            date: 25/06
            client: Sou do Esporte
            status: client
          -
            date:
            status:
      -
        month: Julho
        weeks:
          -
            date: 02/07
            client: Samba Ads
            status: client
          -
            date: 09/07
            client: Raciel
            status: client
          -
            date: 16/07
            client: Danielle Meneses
            status: client
          -
            date: 23/07
            status: free
          -
            date: 30/07
            client: Sala de Ideias
            status: client
      -
        month: Agosto
        weeks:
          -
            date: 06/08
            status: free
          -
            date: 13/08
            client: Alexandre Assed
            status: client
          -
            date: 20/08
            status: free
          -
            date: 27/08
            status: free
          -
            date:
            status:

  schedule_en:
    year: 2013
    data:
      -
        month: June
        weeks:
          -
            date: 04/06
            client: BRtrax
            status: client
          -
            date: 11/06
            client: Darwin Ianuskiewtz
            status: client
          -
            date: 18/06
            status: free
          -
            date: 25/06
            client: Sou do Esporte
            status: client
      -
        month: July
        weeks:
          -
            date: 02/07
            client: Samba Ads
            status: client
          -
            date: 09/07
            client: Raciel
            status: client
          -
            date: 16/07
            client: Danielle Meneses
            status: client
          -
            date: 23/07
            client:
            status: free
          -
            date: 30/07
            client: Sala de Ideias
            status: client
      -
        month: August
        weeks:
          -
            date: 06/08
            status: free
          -
            date: 13/08
            client: Alexandre Assed
            status: client
          -
            date: 20/08
            status: free
          -
            date: 27/08
            status: free
          -
            date:
            status:

### Video infos
video:
  number_of_projects: 30

  projects:
    -
      name: Manager Book
      url: "#"
      image: /images/projetos/video/managerbook.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Samba Ads
      url: "#"
      image: /images/projetos/video/sambaads.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Cleaner
      url: "#"
      image: /images/projetos/video/cleaner.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"
    -
      name: Adstruc
      url: "#"
      image: /images/projetos/video/adstruc.png
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate"

  testimonials:
    -
      name: "Mauro"
      company: "RBM Solutions"
      description: "We appreciated Chili Gum Videos work very much. Since the first time we got in touch we always had a great customer service and everything agreed was done flawlessly. Deadlines were met and all the necessary changes were communicated in advance. The most satisfying of all was the quality of the work delivered, far above expectations. I recommend Chili Gum Videos to everyone"
    -
      name: "Louise Kinane"
      company: "Piriform"
      description: "Chili Gum were a pleasure to work with and we are delighted with the final product! Their work was high quality, turnaround was quick, and they were very flexible in terms of tweaks we requested. We hope work with Chili Gum again soon and have no hesitation recommending them to others."

  schedule:
    year: 2013
    data:
      -
        month: Junho
        weeks:
          -
            date: 04/06
            client: BRtrax
            status: client
          -
            date: 11/06
            client: Darwin Ianuskiewtz
            status: client
          -
            date: 18/06
            status: free
          -
            date: 25/06
            client: Sou do Esporte
            status: client
          -
            date:
            status:
      -
        month: Julho
        weeks:
          -
            date: 02/07
            client: Samba Ads
            status: client
          -
            date: 09/07
            client: Raciel
            status: client
          -
            date: 16/07
            client: Danielle Meneses
            status: client
          -
            date: 23/07
            status: free
          -
            date: 30/07
            client: Sala de Ideias
            status: client

  schedule_en:
    year: 2013
    data:
      -
        month: June
        weeks:
          -
            date: 04/06
            client: BRtrax
            status: client
          -
            date: 11/06
            client: Darwin Ianuskiewtz
            status: client
          -
            date: 18/06
            status: free
          -
            date: 25/06
            client: Sou do Esporte
            status: client
      -
        month: July
        weeks:
          -
            date: 02/07
            client: Samba Ads
            status: client
          -
            date: 09/07
            client: Raciel
            status: client
          -
            date: 16/07
            client: Danielle Meneses
            status: client
          -
            date: 23/07
            client:
            status: free
          -
            date: 30/07
            client: Sala de Ideias
            status: client


